(ns con-hash.core-test
  (:require [clojure.test :refer :all]
            [con-hash.core :refer :all]))

(deftest clockwise-node-test
  (testing "clockwise-node"
    (let [h-nodes (sorted-map
                     200550972 "BOX_4"
                     634766542 "BOX_3"
                    1175924530 "BOX_2"
                    1241078754 "BOX_5"
                    1980158778 "BOX_1")]
      (are [h-i e] (= (clockwise-node h-i h-nodes))
            200000000 "BOX_4"
            200550971 "BOX_4"
            200550972 "BOX_3"
           1100000000 "BOX_2"
           1241000000 "BOX_5"
           1980000000 "BOX_1"
           2990000000 "BOX_4"))))

(deftest hash-nodes-test
  (testing "hash-nodes"
    (are [nodes e]
         (= e (hash-nodes nodes hash))

         (map #(str "BOXEN-" %) (range 1 6))
         (sorted-map -2131596019 "BOXEN-5"
                      1421873742 "BOXEN-1"
                       306002007 "BOXEN-2"
                       788895988 "BOXEN-3"
                      1436113819 "BOXEN-4"))))

(deftest consistent-hash-fn-test
  (testing "consistent-hash-fn"
    (let [h (consistent-hash-fn hash hash)]
      (are [item nodes e] (= e (h item nodes))
           "item-29873" ["node-1"
                         "node-2"
                         "node-3"
                         "node-4"] "node-1"
           "item-29873" ["node-1"
                         "node-2"
                         "node-3"
                         "node-4"
                         "node-5"] "node-1"
           "item-29873" ["node-1"
                         "node-2"
                         "node-3"
                         "node-4"
                         "node-5"
                         "node-6"] "node-1"
           "item-29873" ["node-1"
                         "node-2"
                         "node-3"
                         "node-4"
                         "node-5"
                         "node-6"
                         "node-7"] "node-7"
           "item-29873" ["node-1"
                         "node-2"
                         "node-3"
                         "node-4"
                         "node-5"
                         "node-6"
                         "node-7"
                         "node-8"] "node-7"
           "item-29873" ["node-1"
                         "node-2"
                         "node-3"
                         "node-4"
                         "node-5"
                         "node-6"
                         "node-7"
                         "node-8"
                         "node-9"] "node-7"
           "item-999" ["N1"
                       "N2"
                       "N3"
                       "N4"] "N3"
           "item-999" ["N1"
                       "N2"
                       "N3"
                       "N4"
                       "N5"] "N3"
           "item-999" ["N1"
                       "N2"
                       "N3-X"
                       "N4"
                       "N5"
                       "N6"] "N1"
           "item-999" ["N1"
                       "N2"
                       "N3-X"
                       "N4"
                       "N5"
                       "N6"
                       "N7"] "N1"
           "item-999" ["N1"
                       "N2"
                       "N3-X"
                       "N4"
                       "N5"
                       "N6"
                       "N7"
                       "N8"] "N1"
           "item-999" ["N1-X"
                       "N2"
                       "N3-X"
                       "N4"
                       "N5"
                       "N6"
                       "N7"
                       "N8"] "N4"
           "item-999" ["N1-X"
                       "N2"
                       "N3-X"
                       "N4"
                       "N5"
                       "N6"
                       "N7"
                       "N8"
                       "N9"] "N4"
           "item-999" ["N1-X"
                       "N2"
                       "N3-X"
                       "N4-X"
                       "N5"
                       "N6"
                       "N7"
                       "N8"
                       "N9"] "N7"))))
